#cloud-config
package_update: true
package_upgrade: true
apt_preserve_sources_list: true

packages:
    - build-essential
    - libssl-dev
    - libffi-dev 
    - python3
    - python3-pip
    - r-base
    - gdebi-core
    
apt_sources:
- source: "deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/"
  keyid: E298A3A825C0D65DFD57CBB651716619E084DAB9

write_files:
- content: |
    #!/usr/bin/env bash
    cd /home/ubuntu/
    pip3 install virtualenvwrapper --user
    wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.3.1093-amd64.deb
    gdebi rstudio-server-1.3.1093-amd64.deb
  path: /root/clone.sh
  

runcmd:
  - sudo cp /root/clone.sh /home/ubuntu/clone.sh
  - [ bash, -c, "chmod +x /home/ubuntu/clone.sh" ]
  - [ bash, -c, "chown ubuntu: /home/ubuntu/clone.sh" ]
  - sudo -u ubuntu bash -c 'whoami;/home/ubuntu/clone.sh'